//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropuestasValoraciones
    {
        public int IdValoracion { get; set; }
        public int IdUsuario { get; set; }
        public int IdPropuesta { get; set; }
        public bool Valoracion { get; set; }
    
        public virtual Propuestas Propuestas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
