//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropuestaDonacionInsumo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PropuestaDonacionInsumo()
        {
            this.DonacionInsumo = new HashSet<DonacionInsumo>();
        }
    
        public int IdPropuestaDonacionInsumo { get; set; }
        public int IdPropuesta { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonacionInsumo> DonacionInsumo { get; set; }
        public virtual Propuesta Propuesta { get; set; }
    }
}
