//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SolidamEntities : DbContext
    {
        public static SolidamEntities Instance { get; } = new SolidamEntities();

        private SolidamEntities()
            : base("name=SolidamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Denuncia> Denuncia { get; set; }
        public virtual DbSet<DonacionHorasTrabajo> DonacionHorasTrabajo { get; set; }
        public virtual DbSet<DonacionInsumo> DonacionInsumo { get; set; }
        public virtual DbSet<DonacionMonetaria> DonacionMonetaria { get; set; }
        public virtual DbSet<Propuesta> Propuesta { get; set; }
        public virtual DbSet<PropuestaDonacionHorasTrabajo> PropuestaDonacionHorasTrabajo { get; set; }
        public virtual DbSet<PropuestaDonacionInsumo> PropuestaDonacionInsumo { get; set; }
        public virtual DbSet<PropuestaDonacionMonetaria> PropuestaDonacionMonetaria { get; set; }
        public virtual DbSet<PropuestaReferencia> PropuestaReferencia { get; set; }
        public virtual DbSet<PropuestaValoracion> PropuestaValoracion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
